### ISSUE TITLE
Bitcoin donations don't show up under "top supporters"

### ISSUE THREAD

**Issue by vikstrous** [noisebridge/donate.noisebridge.net#32]
I think bitcoin donations should be labeled as being from "Satoshi Nakamoto" or "Anonymous" and show up in the list with the other donations.

**Comment by patrickod** [comment]
Any ideas on the best way to achieve this? The app currently has no part in the btc donations, and I'm loathe to make this manual.

**Comment by vikstrous** [comment]
For a low security use case like this, it's enough to ping blockchain.info periodically over TLS. You can either do it synchronously and cache the result or do it as a periodic background job. You should be able to use https://github.com/blockchain/api-v1-client-ruby/blob/master/docs/blockexplorer.md#get_address

**Comment by patrickod** [comment]
BTC hasn't been high enough volume so going to close this out for the moment as wontfix
