### ISSUE TITLE
Fix the favicon to have a transparent background

### ISSUE THREAD

**Issue by patrickod** [noisebridge/donate.noisebridge.net#57]
Currently it has a white background which looks crap when the tab background in FF / Chrome isn't white.

**Comment by ChrisAntaki** [comment]
Hey Patrick,

Here's a logo with transparency:
https://github.com/ChrisAntaki/noisebridge-icon/raw/master/noisebridge-icon.png

Here's an example page with the logo as its favicon:
https://chrisantaki.github.io/noisebridge-icon/

Here's the code that page used to reference a PNG icon:
```html
<link rel="shortcut icon" href="noisebridge-icon.png" type="image/png">
```

Looks like a fallback might be needed for iOS Safari, Opera Mini, and IE<=10:
https://caniuse.com/#feat=link-icon-png

Cheers,
Chris

**Comment by ChrisAntaki** [comment]
Actually, it might be easier to just use this multi-size `.ico` file:
https://github.com/ChrisAntaki/noisebridge-icon/raw/master/favicon.ico
