### ISSUE TITLE
Donation form should have YYYY in the example/placeholder field

### ISSUE THREAD

**Issue by robbintt** [noisebridge/donate.noisebridge.net#77]
YY only fails

**Comment by patrickod** [comment]
Should be super easy to edit in-Github if you want to give it a shot. There's a partial for the credit card form.

**Comment by robbintt** [comment]
Fixed here, pushed to master. https://github.com/noisebridge/donate.noisebridge.net/commit/56b4632eb66b3bf77df4597cf973431b3ab9190c
